name: Linux

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  workflow_dispatch:

jobs:
  linux-build:
    strategy:
      matrix:
        compiler: [g++, clang++]
    runs-on: ubuntu-24.04
    env:
      CXX: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v5

      - name: Configure CMake Project
        run: cmake --preset unixlike-debug-dev -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/taocpp-install

      - name: Build project files
        run: cmake --build --preset unixlike-debug-dev

      - name: Run tests
        run: cmake --build --preset unixlike-debug-dev --target test

      - name: Install Taocpp Tuple
        run: cmake --build --preset unixlike-debug-dev --target install
