name: Windows

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  workflow_dispatch:

jobs:
  vs2022:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up MSVC dev cmd (x64)
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: CMake Configure
      shell: pwsh
      run: cmake --preset msvc-release-dev -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/taocpp-install

    - name: Build project files
      run: cmake --build --preset msvc-release-dev

    - name: Run tests
      run: cmake --build --preset msvc-release-dev --target test

    - name: Install Taocpp Tuple
      run: cmake --build --preset msvc-release-dev --target install